### ISSUE TITLE
Can't open map

### ISSUE THREAD

**Issue by EnderRobber101** [senseiwells/ChunkDebug#11]
**Describe the bug**
The essential client chunk debug button is dark and cannot be clicked

**General Info**
1.20.4
Minecraft Version: 
Xaero's minmap,xareo's world map, tweekerroo

**To Reproduce**
Just installing with mods

**Expected behavior**
It should be available to click

**Crash Report / Lastest Log**
There was no crash

**Screenshots / Videos**
If applicable, add screenshots or videos to help explain your problem.

**Additional info**
Add any other info about the problem here.

**Comment by senseiwells** [comment]
You must install ChunkDebug for ChunkDebug to work.
It will be blanked out if ChunkDebug is not installed. If you are playing on a server you need to install ChunkDebug on the server, if you are in singleplayer install it on the client.
