### ISSUE TITLE
Moving past a Chunk Border while the map is being viewed causes a StackOverFlowError

### ISSUE THREAD

**Issue by Howardohyea** [senseiwells/ChunkDebug#14]
**Describe the bug**
Looks like I'm the first person to report this issue, so this might be an isolated case. I'll report this nonetheless because it might help later down the line.
In a 1.21.1 singleplayer world, moving past a chunk border while viewing the minimap OR chunk map crashes my game, this could be achieved by simply having the minimap open and walking, or by opening the Chunk Map while flying and coasting into a neighboring chunk.

I've occasionally had game crashes without having anything open, but this is inconsistent and they have identical crash logs.

**General Info**
Mod Version: ChunkDebug 2.0.0 for 1.21.1
Minecraft Version: 1.21.1
List of other mods: Fabric Loader 0.16.5, Fabric API 0.104.0+1.21.1, Lithium 0.13.0, Sodium 0.5.11+mc1.21

**To Reproduce**
This could be isolated, but this is what's been triggering my crashes:
1. View the chunk borders using `F3 + B`
2. Open the minimap
3. Move past a chunk border

**Crash Report / Latest Log**
All crash logs appear to be identical so I'm only uploading a random one
[crash-2024-09-15_17.21.16-client.txt](https://github.com/user-attachments/files/17005209/crash-2024-09-15_17.21.16-client.txt)

**Additional Details**
I would be happy to provide additional information if it is helpful/required.

**Comment by senseiwells** [comment]
I cannot reproduce this issue with only ChunkDebug and fabric api. Can you please confirm whether this issue exists without the other mods?

If the issue persists then could you please send me a copy of the world with exact coordinates and directions to reproduce. Providing a video of the crash would also be helpful.

**Comment by Howardohyea** [comment]
Welp, jokes on me because I started a new world and I can't reproduce anything now 🤦. I guess it was a fluke or something was messed up with that particular world of mine? After flying around a bit in creative there's no more crashes, consider this bug report meaningless.

**Comment by senseiwells** [comment]
If you re-encounter this issue please re-open this issue
