### ISSUE TITLE
Mod not loading

### ISSUE THREAD

**Issue by Cabbage698** [senseiwells/ChunkDebug#17]
When i launch the game the mod dose not work

**General Info**
Mod Version: 1.20.4
Minecraft Version:  1.20.4
List of other mods:   [✔] replaymod-1.20.4-2.6.20
  [✔] shulkerboxtooltip-fabric-4.1.0+1.20.4
  [✔] sit!-1.2.1+1.20.4
  [✔] sodium-fabric-0.5.8+mc1.20.4
  [✔] tweakeroo-fabric-1.20.4-0.19.3
  [✔] worldedit-mod-7.3.0
    [✔] placeholder-api-2.4.0-pre.1+1.20.4  [✔] architectury-11.1.17-fabric
  [✔] bettercommandblockui-0.5.2-1.20.3
  [✔] bobby-5.1.0+mc1.20.4
  [✔] carpet-tis-addition-v1.65.0-mc1.20.4
  [✔] ChunkDebug-1.20.4-1.1.0
  [✔] cloth-config-13.0.138-fabric
  [✔] dark-loading-screen-1.6.14
  [✔] datapack-reload-helper-1.0
  [✔] discarpet-1.20.4-1.5.4
  [✔] Essential Dependencies
  [✔] essential_1-3-5-5_fabric_1-20-4
  [✔] fabric-api-0.97.2+1.20.4
  [✔] fabric-carpet-1.20.3-1.4.128+v231205
  [✔] fabric-language-kotlin-1.13.0+kotlin.2.1.0
  [✔] framework-fabric-1.20.4-0.7.12
  [✔] g4mespeed-1.4.6-mc1.20.4
  [✔] Gamma-Utils-1.7.19-mc1.20.4
  [✔] litematica-fabric-1.20.4-0.17.4
  [✔] malilib-fabric-1.20.4-0.18.4-alpha.1
  [✔] modmenu-9.2.0

**To Reproduce**
Steps to reproduce the behavior: I have no idea how

**Expected behavior**
Mod function dont work

**Crash Report / Latest Log**
https://mclo.gs/LJtRUZr

**Comment by senseiwells** [comment]
For the versions prior to 1.20.6 you must have [EssentialClient](https://modrinth.com/mod/essentialclient/versions) installed and access ChunkDebug through the EssentialClient menu
