### ISSUE TITLE
Map shows chunks as loaded when they're not when light suppressing

### ISSUE THREAD

**Issue by Ayn4** [senseiwells/ChunkDebug#2]
**Describe the bug**
(single player) When light suppressing to stop chunks from loading, ChunkDebug shows some chunks as being loaded when they're not.

**General Info**
Mod Version: 1.18.2-1.0.3
Minecraft Version: 1.18.2
List of other mods: 
BetterF3-1.2.4
bobby-3.11
capet-extra-1.4.72
carpet-tis-1.37.0
continuity-1.1.0
fabric-api-0.51.1
fabric-carpet-1.4.69+v220331
itemscroller-0.16.0
litematica-0.11.3
lithiuim-0.7..10
malalib-0.12.1
minihud-0.22.0
modmenu-3.2.1
sodium-0.4.1+build.15
tweakeroo-0.13.3
chunk-debug-1.03
essential-client-1.2.3
inventoryprofilesnext 1.3.6

**To Reproduce**
Use a lamp based light suppressor, using a bot to load it.
Wait for chunks to stop loading.
Sometimes chunks will show on the map as loaded when they're not in game.

**Expected behavior**
I expected the map to reflect the game's chunk states.

**Crash Report / Lastest Log**
[latest.log](https://github.com/senseiwells/ChunkDebug/files/9032952/latest.log)

**Screenshots / Videos**
![Screenshot_23_LI](https://user-images.githubusercontent.com/86566581/176999366-bca71536-e38e-48a0-81aa-fdded114bc8f.jpg)

**Additional info**
Admittedly these are extreme conditions that probably cause the issue, so it not working here is understandable but it would be really useful to be able to rely on it for what I'm doing right now ^^ (fast degg bedrock breaker without having to move the player to make the chunks lazy).

**Comment by senseiwells** [comment]
If you open the chunk debug menu and hit the refresh button while holding the control key on your keyboard does that fix the issue?

**Comment by Ayn4** [comment]
![image](https://user-images.githubusercontent.com/86566581/177523137-c97b7e1d-5007-48a2-9860-83963b1f94dd.png)
Not really no, still showing some chunks the wrong way ^^' This one is unloaded but shows as entity ticking.

**Comment by senseiwells** [comment]
I genuinely have no idea how this could be happening, chunk debug sends the client the data based on what the server marks the chunks as... So I don't know how to fix this basically, I will put it on my todo list but I wouldn't expect this to be fixed any time soon, sorry :P

**Comment by senseiwells** [comment]
I haven't directly fixed this bug but it may be fixed with some other bug fixes I have now fixed, try [this version](https://github.com/senseiwells/ChunkDebug/actions/runs/3032568004).

You will need to extract the mod from the artifact

**Comment by senseiwells** [comment]
Closing as stale, also as light suppression is essentially patched this is redundant
